// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpAoErzNTzJe--MjpsOqt_vhjOQ7_aQfQ',
    appId: '1:1016132990959:web:2d7763552828dcdee8681a',
    messagingSenderId: '1016132990959',
    projectId: 'smart-parking-b83eb',
    authDomain: 'smart-parking-b83eb.firebaseapp.com',
    storageBucket: 'smart-parking-b83eb.appspot.com',
    measurementId: 'G-ENMPK6WRMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUYkxj19mPru9ge9JtZukneepIwd0wBsA',
    appId: '1:1016132990959:android:7fe987a41883154de8681a',
    messagingSenderId: '1016132990959',
    projectId: 'smart-parking-b83eb',
    storageBucket: 'smart-parking-b83eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCo59doKdDPIkhPPDatQ-goTayObP5wMo',
    appId: '1:1016132990959:ios:bccefcfe11e33552e8681a',
    messagingSenderId: '1016132990959',
    projectId: 'smart-parking-b83eb',
    storageBucket: 'smart-parking-b83eb.appspot.com',
    iosClientId: '1016132990959-8tjan2rdopvn42b5eac75d3f6hg357j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCo59doKdDPIkhPPDatQ-goTayObP5wMo',
    appId: '1:1016132990959:ios:82482f91f3942116e8681a',
    messagingSenderId: '1016132990959',
    projectId: 'smart-parking-b83eb',
    storageBucket: 'smart-parking-b83eb.appspot.com',
    iosClientId: '1016132990959-ruellkhedq7oeqncjjhfs1vqdfp3ur9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartParking.RunnerTests',
  );
}
